apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nationalparks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nationalparks
    app.kubernetes.io/part-of: nationalparks
  name: nationalparks
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nationalparks
status:
  loadBalancer: {}
